### ISSUE TITLE
Identifiers maximum length

### ISSUE THREAD

**Issue by Pipluppp** [Pipluppp/interpreter#7]
Handle identifiers going past the maximum character length of 31.

**Comment by PaullyMac** [comment]
Will work on this.

**Comment by PaullyMac** [comment]
I actually had a hard time deciding which is which. Initially, when I was coding for this particular issue, my thought process was for, say, an identifier be truncated (if it exceeds the maximum character length of 31).  

So like when I have a `file.txt` containing this, 

>  `string_variable_sting_variable_string_variable = "string";
`

I am thinking that it should output something like this:

`Next token is: 46, Next lexeme is string_variable_sting_variable_s`

Now, for its token, I added a `TokenType` in our header file `token.h` called `ERROR_INVALID_IDENTIFIER` so that we have token that determines if that identifier is an invalid identifier (if I am actually wrong on this point, then feel free to disregard all of my pull request related to this).

Pero at the end, I decided nalang to retain the full identifier by not truncating it. After all, I thought na the `TokenType` `ERROR_INVALID_IDENTIFIER` will act as our token when it scanned an identifier that exceeds max length of 31.

Check #18
